### ISSUE TITLE
suggestion: avoid code generation

### ISSUE THREAD

**Issue by alita-moore** [monarch-initiative/ontogpt#102]
Sorry if I'm talking into the void or beating a dead horse, but just a heads up that it's generally ill advised to generate code like you do here (i.e. yaml -> pydantic etc.). I just noticed this and thought it may be helpful to point that out as I'm having difficulty understanding the codebase and also it seems quite finicky in terms of execution.

Nevertheless I love the repo and its function; awesome!

**Comment by cmungall** [comment]
Thanks for the comment and the interest @alita-moore! Checking in derived products is one of these things we have a lot of internal discussions about.

The general paradigm of dual linkml yaml and pydantic is a standard one when we use our linkml.io framework. We love pydantic, but the yaml provides additional expressivity (for example, we have one source of truth for the schema, how to restrict enums/ontology terms on the terminal nodes).

Perhaps at some stage we will have things such that the pydantic is generated more dynamically but for now there is a lot of advantage like making things transparent for IDEs etc.

Glad you like the repo! 🙏
