### ISSUE TITLE
Documentation: provide example of custom LinkML model

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/ontogpt#13]
I tried

```
ontogpt extract -t path/to/templates/phenotype.yaml abstract.txt
```

but got:

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/matentzn/ws/ontogpt/src/ontogpt/templates/path/to/templates/phenotype.yaml'`
```

**Comment by cmungall** [comment]
The argument for `-t` has to be the name of a template in the templates folder.

We should make it such that it can be any of:

1. a path to yaml (with compilation to pydantic happening dynamically)
2. a path to a folder with yaml and py
3. the name of a schema that is discoverable via a plugin framework

For now I would suggest making PRs and we will err on the side of over-inclusion of different people's schemas in the main repo (and people can always make long running forks if they don't want to share). As we may need to refactor a bit having them all mono style is probably best for now. But there will come a point where this won't scale... not there yet though!

**Comment by nlharris** [comment]
should i create a linkml enhancement ticket (in the linkml repo) for your "we should make it" list?

**Comment by cmungall** [comment]
this would be an ontogpt piece of functionality

**Comment by serenalotreck** [comment]
Not sure if this is the right place for this question -- is there a way to integrate a custom LinkML schema with the pip-installed version of the package, as opposed to needing to fork the repo?

**Comment by nlharris** [comment]
Hi @serenalotreck, this seems like a question that is not that closely related to this issue. Can you open a new issue, or try asking on the LinkML community Slack?

**Comment by caufieldjh** [comment]
This question is still related, but I'll transfer it to its own issue so I ensure it gets into the documentation.
