### ISSUE TITLE
Add interface for abstract OpenAI-equivalent API 

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#143]
From #70: 
> Currently, I cannot use ontoGPT in my organization as it is due to security concerns around external APIs like OpenAI's. To address this issue, I suggest exploring the possibility of using open-source, local LLMs and their APIs as an alternative to OpenAI's API.

I have a similar use case, however, could it ever be abstracted even further, with an option to use _in-house_ LLM services? We are currently working on such a ChatGPT alternative, and it would be amazing to simply plug in that API for ontoGPT...

_Originally posted by @remerjohnson in https://github.com/monarch-initiative/ontogpt/issues/70#issuecomment-1604285035_

**Comment by cmungall** [comment]
llm is an awesome library
https://llm.datasette.io/

It was originally for command line usage (fun and really handy for testing
and quick ad-hoc queries)

It now provides a first class API:
https://llm.datasette.io/en/stable/python-api.html

It has a really nice plugin architecture with lots of open models available
as plugins
https://llm.datasette.io/en/stable/plugins/index.html

Plugins here:
https://github.com/simonw/llm-plugins

The API abstracts away implementation specific differences

We should also consider making our logging consistent or just using it
directly
https://llm.datasette.io/en/stable/logging.html

**Comment by caufieldjh** [comment]
Just based on the way this API is set up, we can move away from some of the langchain-driven implementation to this

**Comment by caufieldjh** [comment]
Going to prioritize this since I've found that some extractions, like disease or phenotype, work surprisingly well with a small model (like `orca-mini-3b`) and `llm`. Not sure what was going wrong with how `langchain` interfaced with the `gpt4all` models but I'm seeing some really usable results now.

**Comment by caufieldjh** [comment]
Now supported by #373
