### ISSUE TITLE
Add parser for PubMedCentral full texts

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#154]
We'd like to work with larger sets of full texts from PubMed (Central).
These may be downloaded here: https://www.ncbi.nlm.nih.gov/pmc/tools/openftlist/
But we still need functions to:
1. Index PMC docs
2. Retrieve texts for a list of PMIDs
3. Pass segments of full texts to extract function (assuming the full doc will be longer than context length) - ideally filterable by some segment, or defaulting to the first n tokens or so

**Comment by justaddcoffee** [comment]
Access to full text of articles would help with both KG-IBD and Jens/Ravi's kidney project

**Comment by justaddcoffee** [comment]
yep, I guess accessing through the API for now would be the quickest solution

**Comment by caufieldjh** [comment]
This is complete; see #156

**Comment by caufieldjh** [comment]
and by complete I mean "through the API", not "downloaded and indexed", but we can re-open this if that becomes necessary
