### ISSUE TITLE
Minor formatting issue on https://monarch-initiative.github.io/ontogpt

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/ontogpt#193]
Screenshot:

<img width="431" alt="Screenshot 2023-09-04 at 4 54 53 PM" src="https://github.com/monarch-initiative/ontogpt/assets/348704/746f39d2-dfdd-4062-a172-121d0c57e1f1">

Maybe the three-backtick thing doesn't work inside < details >? or maybe it doesn't work if there are any spaces before it?

The source is in https://github.com/monarch-initiative/ontogpt/edit/main/README.md

**Comment by nlharris** [comment]
> maybe it doesn't work if there are any spaces before it?

That's not the solution -- taking out the initial spaces before the three backticks breaks the whole section. Maybe it's just not possible to nest the backtick yaml block inside a details section.

**Comment by caufieldjh** [comment]
Fixed - the trick is to have a newline after the `summary` line _and_ to have no spaces preceding the backticks closing the code section.
