### ISSUE TITLE
Evaluate relation extraction on OMIM gene to disease

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#20]
OMIM gene to disease relations are a good biomedical example of relations, and there are curated sets of these relations (https://maayanlab.cloud/Harmonizome/dataset/OMIM+Gene-Disease+Associations).
Can we use OntoGPT/SPIRES to, starting with either OMIM profiles for each gene OR the cited papers, extract the same G2D association?

**Comment by cmungall** [comment]
We have some eval code in for d2p

I think d2g is a good baseline test. I think this should be quite easy, *provided* the right paper has been selected, describing a mendelian association

**Comment by caufieldjh** [comment]
Going to close this issue as I'm not certain there's a way to retrieve individual abstracts for each association from this data set (i.e., it doesn't include annotated text) so a formal comparison isn't possible.
