### ISSUE TITLE
Is there a way to integrate a custom LinkML schema with the pip-installed version of the package?

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#222]
> Not sure if this is the right place for this question -- is there a way to integrate a custom LinkML schema with the pip-installed version of the package, as opposed to needing to fork the repo?

_Originally posted by @serenalotreck in https://github.com/monarch-initiative/ontogpt/issues/13#issuecomment-1735979072_

**Comment by caufieldjh** [comment]
Hi @serenalotreck, the short answer is Yes, though it can be a bit messy.
Once creating a custom schema and including annotations like those in the repo (with sets of annotators, at a minimum), then you'll need to generate the Pydantic version with linkml's `gen-pydantic` tool - this should be installed as part of the ontogpt dependencies. Something like this should work:
```
gen-pydantic --pydantic_version 2 custom_schema.yaml > custom_schema.py
```
Then move both the .yaml and the .py versions to the `templates` directory of wherever it is installed. In a virtual environment named `temp` that's probably something like `/tempog/lib/python3.9/site-packages/ontogpt/templates`.

You should then be able to use the schema like any of the other templates:
```
$ ontogpt -vvv extract -t custom_schema -i input.txt
```

**Comment by serenalotreck** [comment]
Looks like that worked, thanks!
