### ISSUE TITLE
Can't import ontogpt - openAI object gives errors

### ISSUE THREAD

**Issue by mamscience** [monarch-initiative/ontogpt#248]
Hi

I tried to import ontogpt as a module in another app. I'm following the method used in the webapp, so importing certain modules and then using
```
engine = get_engine(datamodel)
ann = engine.extract_from_text(text)
```

unfortunately, it throws errors, to be specific: in creating the openAI object.
```
ERROR:ontogpt.clients.openai_client:OpenAI API connection error: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>
INFO:ontogpt.clients.openai_client:Retrying 1 of 3 after 4 seconds...
ERROR:ontogpt.clients.openai_client:OpenAI API connection error: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>
INFO:ontogpt.clients.openai_client:Retrying 2 of 3 after 16 seconds...
```

When I check the openai_client, in line 63, when I change the _model=engine_ to _engine="gpt-3.5-turbo"_ the error changes
```
ERROR:ontogpt.clients.openai_client:OpenAI API connection error: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
```

Which is really strange because the key is correct. Regional API endpoint I only know from Azure, but I'm not calling Azure here.

To be clear:

- I'm using the latest version of ontogpt
- I'm using the latest version of openai python module
- the CLI works fine
- the webapp works (it threw some errors I think, but not related to this).

I'm totally out of options, what could be the reason of this bug?

**Comment by mamscience** [comment]
find the bug, fixed it

**Comment by caufieldjh** [comment]
Thanks!
