### ISSUE TITLE
Add links to presentation videos and slides within the docs

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#256]
This one in particular: https://docs.google.com/presentation/d/1CosJJe8SqwyALyx85GWkw9eOT43B4HwDlAY2CmkmJgU/edit#slide=id.g23cd0d4895a_0_168
And the recording: https://www.youtube.com/watch?v=rt3wobA9hEs&t=1955s

There are others, so a dedicated page for tutorials and presentations may be in order.

**Comment by nlharris** [comment]
You beat me to it, I was just about to make a ticket for this!

**Comment by nlharris** [comment]
@yy20716 just reminded us in email about this.

What is the best way to proceed with this? I could easily add a section to the README, or I could (with a bit more work) create a new "Tutorials and presentations" (?) page in https://github.com/monarch-initiative/ontogpt/tree/main/docs. LMK and I can work on this.

**Comment by caufieldjh** [comment]
Thanks @nlharris - probably best for those to go in the README so they're most findable.
