### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by LicoriceLin** [monarch-initiative/ontogpt#265]
1. Openai has upgraded to 1.0+ thus raise many incompatibility issues. `openai migrate` can help, but there are still some lines I need to modify by myself. 
2. `pip install ontogpt` will install Pydantic=1.10 automatically, which will also raise error.

**Comment by cmungall** [comment]
1. I think we should track the `llm` package here: https://github.com/simonw/llm/issues/325

**Comment by caufieldjh** [comment]
Well spotted - looking into it.

**Comment by caufieldjh** [comment]
Will still need to update code for that openai >=1.0, but is currently addressed by #271
