### ISSUE TITLE
Error when downloading gpt4all models, llm can't find the model to download

### ISSUE THREAD

**Issue by doubleplusplus** [monarch-initiative/ontogpt#266]
`poetry run ontogpt complete example.txt -m nous-hermes-13b`

 

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/jamie/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/jamie/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/jamie/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/jamie/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/jamie/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/jamie/ontogpt/src/ontogpt/cli.py", line 1555, in complete
>     results = chain_gpt4all_model(model=c, prompt_text=text)
>   File "/home/jamie/ontogpt/src/ontogpt/utils/gpt4all_runner.py", line 22, in chain_gpt4all_model
>     return raw_output.text()
>   File "/home/jamie/.conda/envs/onto/lib/python3.9/site-packages/llm/models.py", line 108, in text
>     self._force()
>   File "/home/jamie/.conda/envs/onto/lib/python3.9/site-packages/llm/models.py", line 105, in _force
>     list(self)
>   File "/home/jamie/.conda/envs/onto/lib/python3.9/site-packages/llm/models.py", line 90, in __iter__
>     for chunk in self.model.execute(
>   File "/home/jamie/.conda/envs/onto/lib/python3.9/site-packages/llm_gpt4all.py", line 111, in execute
>     gpt_model = GPT4All(self.filename())
>   File "/home/jamie/.conda/envs/onto/lib/python3.9/site-packages/gpt4all/gpt4all.py", line 97, in __init__
>     self.config: ConfigType = self.retrieve_model(model_name, model_path=model_path, allow_download=allow_download, verbose=verbose)
>   File "/home/jamie/.conda/envs/onto/lib/python3.9/site-packages/llm_gpt4all.py", line 23, in retrieve_model
>     return _GPT4All.retrieve_model(model_name, model_path, allow_download, verbose)
>   File "/home/jamie/.conda/envs/onto/lib/python3.9/site-packages/gpt4all/gpt4all.py", line 187, in retrieve_model
>     config["path"] = GPT4All.download_model(model_filename, model_path, verbose=verbose, url=url)
>   File "/home/jamie/.conda/envs/onto/lib/python3.9/site-packages/gpt4all/gpt4all.py", line 234, in download_model
>     response = make_request()
>   File "/home/jamie/.conda/envs/onto/lib/python3.9/site-packages/gpt4all/gpt4all.py", line 229, in make_request
>     raise ValueError(f'Request failed: HTTP {response.status_code} {response.reason}')
> ValueError: Request failed: HTTP 404 Not Found
> 

Then I manually downloaded the nous-hermes-13b model from HuggingFace and put it in folder `~/.cache/gpt4all/`, but still got the same error

**Comment by TribeDH** [comment]
I'm having a similar issue, specifically when I try to use ggml llms it always raise the same error:

Traceback (most recent call last):
  File "/opt/conda/envs/ontogpt-env/lib/python3.10/site-packages/llm/__init__.py", line 92, in get_model
    return aliases[name]
KeyError: 'ggml-vicuna-13b-1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/ontogpt-env/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/opt/conda/envs/ontogpt-env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/ontogpt-env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/ontogpt-env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/ontogpt-env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/ontogpt-env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mathias.berti/ontogpt/src/ontogpt/cli.py", line 323, in extract
    ke = GPT4AllEngine(template=template, model=model_name, **kwargs)
  File "<string>", line 22, in __init__
  File "/home/mathias.berti/ontogpt/src/ontogpt/engines/gpt4all_engine.py", line 61, in __post_init__
    self.loaded_model = set_up_gpt4all_model(self.model)
  File "/home/mathias.berti/ontogpt/src/ontogpt/utils/gpt4all_runner.py", line 12, in set_up_gpt4all_model
    model = llm.get_model(modelname)
  File "/opt/conda/envs/ontogpt-env/lib/python3.10/site-packages/llm/__init__.py", line 94, in get_model
    raise UnknownModelError("Unknown model: " + name)
llm.UnknownModelError: 'Unknown model: ggml-vicuna-13b-1'

Am I missing something or is it a systematic error? Thanks in advance.

**Comment by caufieldjh** [comment]
Hi @doubleplusplus and @TribeDH , looks like it's related to this issue: https://github.com/nomic-ai/gpt4all/issues/1567
So there are fixes for this in OntoGPT dependencies - we'll just need to update to take advantage of them.
Will update this issue once that's ready.

**Comment by caufieldjh** [comment]
Now a non-issue as we use `litellm` and `ollama` instead of `gpt4all` as of #373
