### ISSUE TITLE
Run ontogpt on all files in a directory

### ISSUE THREAD

**Issue by serenalotreck** [monarch-initiative/ontogpt#276]
I'd like to run ontogpt over all files in a directory, and send the output to a file for each input file.

Is there an easier/integrated way to do this compared to just writing a bash script to run the command over each file?

Thanks!

**Comment by serenalotreck** [comment]
In case a bash script is the best way, here's what I did in case anyone else wants to do the same thing:

```
#!/bin/bash
total=$(ls $1 -1 | wc -l)
echo $total
for FILE in $1*; do
	outname="$2$(basename ${FILE})"
	ontogpt extract -i $FILE -t desiccation > $outname
done | tqdm --total $total
>> /dev/null
```

where I passed the input and output directories as arguments for `$1` and `$2`

**Comment by caufieldjh** [comment]
Hi @serenalotreck - this is now an option for the `extract` command through the CLI. Just pass the path to the directory containing your input files through the `-i` option. One caveat: it is assumed that all input files will end in .txt, for now at least.
