### ISSUE TITLE
Makefile requires some configuration to process custom model

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#28]
The README says running `make` is sufficient to get Pydantic from LinkML YAML, but the list of templates is hard-coded into the Makefile. Including a project.Makefile with a ready-to-update `TEMPLATES` list (and updating the docs accordingly) may make it easier to update.

**Comment by cmungall** [comment]
Possible dupe with #13

**Comment by caufieldjh** [comment]
Yep, the short-term solution for this and #13 is the same - I'll do a PR to make this process easier but will hold off on enabling running arbitrary YAMLs for now

**Comment by cmungall** [comment]
we can also add a dynamic compilation step. 

this requires linkml which is normally only a dev dependency (typically we want dependency on linkml-runtime only). however, we are already pulling in linkml-owl which pulls in linkml

at some stage we can look at splitting dependencies a bit into a sensible extras/plugin arch.. we do that a bit now with the recipe scraper. for now it's a bit of a crazy large dependency tree but doesn't seem to be causing any issues so far...
