### ISSUE TITLE
Need to change OpenAI endpoint?

### ISSUE THREAD

**Issue by dosumis** [monarch-initiative/ontogpt#320]
I'm getting this consistently:

WARNING:ontogpt.clients:llm_gpt4all module not found. GPT4All support will be disabled.

Does the client endpoint need to change?

**Comment by caufieldjh** [comment]
Hi @dosumis - is this with a fresh pip install, and does the warning still appear if you install the `gpt4all` extras?
Using GPT4All models is optional since the framework supporting them has some specific environment requirements, but OpenAI endpoints should work without GPT4All support.

**Comment by dosumis** [comment]
Closing.  I was having other problems and was fooled by the warning message into thinking this was the root cause.  I'll make a separate ticket for the real issue.
