### ISSUE TITLE
OWL_Export test run error

### ISSUE THREAD

**Issue by OldskiGinger** [monarch-initiative/ontogpt#338]
Hi, I am a coding beginner. Just succeeded installing OntoGPT. 
OpenAI key setting, text completion, individual knowledge extraction function all fine. But when I started redoing ontology_exports as described in the guide, error happened always. Is this supposed to be something wrong with `owl_exporter.py`?

Successful below：
```ontogpt extract -t recipe -i /Users/j.rockski/Desktop/ontogpt-main/tests/input/cases/recipe-spaghetti.txt -m gpt-3.5-turbo -o spaghetti_extracted.txt```

with the extracted knowledge：
 

```
extracted_object:
  url: AUTO:13e8c81e-73ed-445b-9931-8f13f444182e
  label: SIMPLE SPAGHETTI
  description: A simple spaghetti recipe with tomato sauce and hamburger meat.
  ingredients:
    - food_item:
        food: FOODON:03316347
        state: None
      amount:
        value: '1'
        unit: AUTO:small
...

```

A failure example below：
```ontogpt extract -t recipe -i /Users/j.rockski/Desktop/ontogpt-main/tests/input/cases/recipe-spaghetti.txt -m gpt-3.5-turbo -o spaghetti_extracted.owl -O owl```

with errors shown as below：

`Setting url [AUTO:4dbbb2e2-a426-438c-bbcf-e052d26fcf29] to AUTO:_ROOT for Recipe
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
WARNING:root:File "<file>", line 329, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 341, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: biolink
Traceback (most recent call last):
  File "/Users/j.rockski/anaconda3/bin/ontogpt", line 8, in <module>
    sys.exit(main())
  File "/Users/j.rockski/anaconda3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/j.rockski/anaconda3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/j.rockski/anaconda3/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/j.rockski/anaconda3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/j.rockski/anaconda3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/j.rockski/anaconda3/lib/python3.10/site-packages/ontogpt/cli.py", line 341, in extract
    write_extraction(results, output, output_format, ke)
  File "/Users/j.rockski/anaconda3/lib/python3.10/site-packages/ontogpt/cli.py", line 115, in write_extraction
    exporter.export(results, output, knowledge_engine.schemaview)
  File "/Users/j.rockski/anaconda3/lib/python3.10/site-packages/ontogpt/io/owl_exporter.py", line 51, in export
    output.write(str(doc).encode("utf-8"))  # type: ignore
  File "/Users/j.rockski/anaconda3/lib/python3.10/codecs.py", line 377, in write
    data, consumed = self.encode(object, self.errors)
TypeError: utf_8_encode() argument 1 must be str, not bytes
`
This debugging is too hard for a newbie, even with ChatGPT‘s help. Can someone help me out? Thx a lot!

**Comment by caufieldjh** [comment]
Hi @OldskiGinger - thanks for your issue.
Are you using the most recent version of `ontogpt`? That's currently v0.3.8 - you can check with `pip list` and find ontogpt, or use `pip list | grep ontogpt`.
I ask because this version includes a fix for this `TypeError` with OWL exports.

**Comment by caufieldjh** [comment]
I was able to successfully complete this command on `ontogpt` v0.3.8 -
```
$ ontogpt extract -t recipe -i recipe-spaghetti.txt -m gpt-3.5-turbo -o spaghetti_extracted.owl -O owl
```
Please let me know if that doesn't work for you.

**Comment by OldskiGinger** [comment]
I just now reinstalled ontogpt from `0.3.6` to `0.3.8`. Issues with `owl_exporter.py `might have been solved, while new problem comes.

I ran again the same code
`ontogpt extract -t recipe -i /ontogpt-main/tests/input/cases/recipe-spaghetti.txt -m gpt-3.5-turbo -o spaghetti_extracted.owl -O owl`

A new warning came as 
`
WARNING:root:Could not find any mappings for FOODON:03490213
WARNING:root:Could not find any mappings for FOODON:03490213
Setting url [AUTO:38e397af-1c21-4e48-8b7d-e404f0a00f95] to AUTO:_ROOT for Recipe
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
WARNING:root:File "<file>", line 335, col 19: Unrecognized prefix: rdf
`

When not using `-O owl` to export ontology, only`WARNING:root:Could not find any mappings for FOODON:03490213` was shown and could nevertheless continue extracting.

But with `-O owl` it warned with `Unrecognized prefix: rdf`. From my understanding, still issue on `owl_exporter.py `?

**Comment by OldskiGinger** [comment]
forgot to @caufieldjh 😊.
thx in advance for your help!

**Comment by caufieldjh** [comment]
The warning you're seeing is because the `recipe` template doesn't explicitly define the `rdf` prefix. The generated owl output should still get the correct mapping between prefix and namespace here (`Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )`) so the output should still be completely valid. 
I'll add a quick fix to the template(s) to ensure this warning doesn't keep appearing.

**Comment by OldskiGinger** [comment]
> The warning you're seeing is because the `recipe` template doesn't explicitly define the `rdf` prefix. The generated owl output should still get the correct mapping between prefix and namespace here (`Prefix( rdf: = <http://www.w3.org/1999/02/22-rdf-syntax-ns#> )`) so the output should still be completely valid.
> I'll add a quick fix to the template(s) to ensure this warning doesn't keep appearing.

thx, problem solved. Really help me a lot :)

Besides, I am trying to build an industrial-production-specific SPIRES. I found the upper level production ontology built by Industrial Foundry Ontology. Do you have any suggestions how to inverse-engineeringly design a template using an exsisting ontology, e.g. https://github.com/iofoundry/ontology

Or just manual work on template editing makes more sense?

**Comment by cmungall** [comment]
You can start a new issue with questions specific to your use case if you like, I'm interested to hear more, I presented on lessons learned from OBO to IOF a few years ago: https://docs.google.com/presentation/d/1BmFuHSl_Kwn8T4M3cKnkBl2k8O-8iKqH-VToygl53X0/edit#slide=id.p

The template/schema really depends on your task

**Comment by caufieldjh** [comment]
Definitely an interesting use case!
As @cmungall notes, I'm going to move that question to a new issue.
