### ISSUE TITLE
Make it easier to use custom schemas 

### ISSUE THREAD

**Issue by vemonet** [monarch-initiative/ontogpt#384]
Using custom schemas seems to be an important part for using this tool in new systems

The current solution is quite technical, requiring to clone the repo and run a `Makefile` process: https://monarch-initiative.github.io/ontogpt/custom/ 

Are there plans to make this more straightforward? e.g. by directly passing the YAML schema through the CLI `ontogpt -t mylinkmlschema.yml` or are there limitations that prevent to do it this way easily?

**Comment by caufieldjh** [comment]
Done - this will be in the next release.

**Comment by vemonet** [comment]
Nice, thanks!
