### ISSUE TITLE
ERROR: Could not build wheels for adeft, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by konashevich** [monarch-initiative/ontogpt#387]
returns error when installing using any of the following commands:
`pip install ontogpt`
`pip install ontogpt[web]`
`pip install ontogpt[gpt4all,web]`

Text of the error: 

> Building wheels for collected packages: adeft
>   Building wheel for adeft (pyproject.toml) ... error
>   error: subprocess-exited-with-error
> 
>   × Building wheel for adeft (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [52 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build\lib.win-amd64-cpython-311
>       creating build\lib.win-amd64-cpython-311\adeft
>       copying src\adeft\disambiguate.py -> build\lib.win-amd64-cpython-311\adeft
>       copying src\adeft\discover.py -> build\lib.win-amd64-cpython-311\adeft
>       copying src\adeft\locations.py -> build\lib.win-amd64-cpython-311\adeft
>       copying src\adeft\recognize.py -> build\lib.win-amd64-cpython-311\adeft
>       copying src\adeft\util.py -> build\lib.win-amd64-cpython-311\adeft
>       copying src\adeft\__init__.py -> build\lib.win-amd64-cpython-311\adeft
>       creating build\lib.win-amd64-cpython-311\adeft\download
>       copying src\adeft\download\download.py -> build\lib.win-amd64-cpython-311\adeft\download
>       copying src\adeft\download\__init__.py -> build\lib.win-amd64-cpython-311\adeft\download
>       copying src\adeft\download\__main__.py -> build\lib.win-amd64-cpython-311\adeft\download
>       creating build\lib.win-amd64-cpython-311\adeft\gui
>       copying src\adeft\gui\__init__.py -> build\lib.win-amd64-cpython-311\adeft\gui
>       creating build\lib.win-amd64-cpython-311\adeft\modeling
>       copying src\adeft\modeling\classify.py -> build\lib.win-amd64-cpython-311\adeft\modeling
>       copying src\adeft\modeling\label.py -> build\lib.win-amd64-cpython-311\adeft\modeling
>       copying src\adeft\modeling\__init__.py -> build\lib.win-amd64-cpython-311\adeft\modeling
>       creating build\lib.win-amd64-cpython-311\adeft\nlp
>       copying src\adeft\nlp\nlp.py -> build\lib.win-amd64-cpython-311\adeft\nlp
>       copying src\adeft\nlp\__init__.py -> build\lib.win-amd64-cpython-311\adeft\nlp
>       creating build\lib.win-amd64-cpython-311\adeft\score
>       copying src\adeft\score\score.py -> build\lib.win-amd64-cpython-311\adeft\score
>       copying src\adeft\score\__init__.py -> build\lib.win-amd64-cpython-311\adeft\score
>       creating build\lib.win-amd64-cpython-311\adeft\gui\ground
>       copying src\adeft\gui\ground\ground.py -> build\lib.win-amd64-cpython-311\adeft\gui\ground
>       copying src\adeft\gui\ground\__init__.py -> build\lib.win-amd64-cpython-311\adeft\gui\ground
>       running egg_info
>       writing src\adeft.egg-info\PKG-INFO
>       writing dependency_links to src\adeft.egg-info\dependency_links.txt
>       writing requirements to src\adeft.egg-info\requires.txt
>       writing top-level names to src\adeft.egg-info\top_level.txt
>       reading manifest file 'src\adeft.egg-info\SOURCES.txt'
>       reading manifest template 'MANIFEST.in'
>       adding license file 'LICENSE'
>       writing manifest file 'src\adeft.egg-info\SOURCES.txt'
>       copying src\adeft\nlp\stopwords.json -> build\lib.win-amd64-cpython-311\adeft\nlp
>       copying src\adeft\score\_score.c -> build\lib.win-amd64-cpython-311\adeft\score
>       copying src\adeft\score\_score.pyx -> build\lib.win-amd64-cpython-311\adeft\score
>       copying src\adeft\score\permutations.pyx -> build\lib.win-amd64-cpython-311\adeft\score
>       creating build\lib.win-amd64-cpython-311\adeft\gui\ground\static
>       copying src\adeft\gui\ground\static\ground.css -> build\lib.win-amd64-cpython-311\adeft\gui\ground\static
>       copying src\adeft\gui\ground\static\scripts.js -> build\lib.win-amd64-cpython-311\adeft\gui\ground\static
>       creating build\lib.win-amd64-cpython-311\adeft\gui\ground\templates
>       copying src\adeft\gui\ground\templates\input.jinja2 -> build\lib.win-amd64-cpython-311\adeft\gui\ground\templates
>       running build_ext
>       building 'adeft.score._score' extension
>       error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for adeft
> Failed to build adeft
> ERROR: Could not build wheels for adeft, which is required to install pyproject.toml-based projects
> 
> (.venv) c:\Users\akona\OneDrive\Dev\OntoGPT>

**Comment by caufieldjh** [comment]
Hi @konashevich - issues with `adeft` I've encountered with this software in the past had to do with missing `libgcc` - see https://github.com/monarch-initiative/ontogpt/pull/306#issuecomment-1889841519

Does the install work if you install the MS C++ build tools from https://visualstudio.microsoft.com/visual-cpp-build-tools/ ?
I think it's possible to install and link the compiler library on Windows independently of the build tools.

This is a dependency of a dependency, so it may also be possible to make it optional if it causes install issues.

**Comment by abhishekbiswas772** [comment]
yes it works by install ms build tools

**Comment by caufieldjh** [comment]
OK, great. Closing; will reopen if this comes up again.
