### ISSUE TITLE
Add the possibility to disable or customize grounding

### ISSUE THREAD

**Issue by vemonet** [monarch-initiative/ontogpt#4]
When running `ontogpt` getting the raw output from GPT models is quite fast (less than 5s), but the process of grounding the extracted entities is really slow (it can take minutes)

It is useful to give a default solution for grounding entities, but it would be practical to enable developers to choose which system they want to use for grounding

An easy way to implement this would be to add a parameter to the `KnowledgeEngine` to enable/disable grounding when extracting text. So that the developers can choose to implement their own grouding system after retrieving the raw output. 

For example in my case I would be interested to use the SRI NameResolution API (https://name-resolution-sri.renci.org/docs)

Let me know if you are interested in this feature, I can create a pull request as I already implemented it in my fork for the SPINES engine

**Comment by cmungall** [comment]
Hi @vemonet! Sorry didn't see these before. 

You can now pass `--skip-annotator`. The string must match the string in the schema, e.g `--skip-annotator gilda:`. You can pass multiple.

Currently the SRI service is used for normalization but it's not very configurable..

**Comment by vemonet** [comment]
Thanks!
