### ISSUE TITLE
Textract plugin fails to install

### ISSUE THREAD

**Issue by timalamenciak** [monarch-initiative/ontogpt#412]
Textract 1.6.5 has some problems in its build file which causes the install to fail - documented here: https://github.com/deanmalmgren/textract/issues/476

The only workaround that I have found to work has been installing textract-py3 - a minimally maintained version without this build vulnerability: https://github.com/KyleKing/textract-py3

However, when I try to point OntoGPT at a PDF, it hangs. Presumably it's not trying to use textract-py3 and is looking for vanilla textract.

**Comment by caufieldjh** [comment]
Strange - I'm unable to reproduce this issue.
Installing with pip (as `pip install ontogpt[textract]`) or with poetry (as `poetry install --extras textract`) both appear to work without issue. Of course, in both cases it's installing textract 1.5.0, which is pretty old, on Python 3.10.
I'll enable using `textract-py3` as an optional dependency.

**Comment by caufieldjh** [comment]
OK, please let me know if PDF processing works after removing `textract` and installing the `textract-py3` extra.

**Comment by timalamenciak** [comment]
Installing the repo version seemed to work off the bat - it installs `textract` 1.5.0, which may not have this problem.

Of course now `textract` throws an error with the PDFs because of some undefined characters but I think that is beyond the scope of this issue request. Thanks for the quick response.
