### ISSUE TITLE
OntoGPT is exporting YAML even with JSON flag

### ISSUE THREAD

**Issue by timalamenciak** [monarch-initiative/ontogpt#420]
Running OntoGPT latest version in Poetry shell 3.12. It seems to be ignoring the json formatting flag. HTML formatting works correctly.

The command:

`ontogpt extract -t ../trek.yaml -i "Shantz and Price 2006.txt" -o shantzprice2.json --output-format json`

The output (minus the prompts and text):

` 

extracted_object:
  id: 30930101-6014-46dd-9b42-e4be6801b338
  label: Restoration of the Bois-des-Bel Peatland, Quebec
  dois: AUTO:10.1016/j.jhydrol.2006.06.002
  management_actions:
    - ENVTHES:21296
    - AUTO:construction%20of%20bunds
    - ENVTHES:20766
    - AUTO:spreading%20of%20Sphagnum%20diaspores
    - ENVTHES:20854
  target_species:
    - NCBITAXON:13804
    - NCBITAXON:46326
  ecosystem_types:
    - ENVO:00000044
    - ENVTHES:21803
  study_sites:
    - GAZ:00418987
    - AUTO:47.8833%C2%B0%20N%2C%2069.4500%C2%B0%20W
  degradation_types:
    - ENVTHES:21803
    - ENVO:01000694
    - ENVTHES:21509
    - ENVTHES:10016
named_entities:
  - id: AUTO:10.1016/j.jhydrol.2006.06.002
    label: 10.1016/j.jhydrol.2006.06.002
  - id: ENVTHES:21296
    label: blocking of drainage ditches
  - id: AUTO:construction%20of%20bunds
    label: construction of bunds
  - id: ENVTHES:20766
    label: application of straw mulch
  - id: AUTO:spreading%20of%20Sphagnum%20diaspores
    label: spreading of Sphagnum diaspores
  - id: ENVTHES:20854
    label: application of phosphorus fertilizer
  - id: NCBITAXON:13804
    label: Sphagnum mosses
  - id: NCBITAXON:46326
    label: Eriophorum
  - id: ENVO:00000044
    label: peatland
  - id: ENVTHES:21803
    label: ombrotrophic peatland
  - id: GAZ:00418987
    label: Bois-des-Bel peatland
  - id: AUTO:47.8833%C2%B0%20N%2C%2069.4500%C2%B0%20W
    label: 47.8833° N, 69.4500° W
  - id: ENVO:01000694
    label: subsidence
  - id: ENVTHES:21509
    label: increased runoff
  - id: ENVTHES:10016
    label: evaporation loss
`

**Comment by caufieldjh** [comment]
The solution here will be to add a JSON writer, because OntoGPT doesn't have that yet!
