### ISSUE TITLE
Update output options for multilingual analysis

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#438]
The multilingual analysis function doesn't use the output exporters in the CLI.
It should be able to use those options rather than opening its own output file - minimally, it should be able to append results to the same file rather than attempting to re-open the same file anew each time.

See https://github.com/monarch-initiative/ontogpt/blob/23399505db7052ea663d446d114cde16e4fb8c33/src/ontogpt/cli.py#L1504-L1519

**Comment by leokim-l** [comment]
Using 
`ontogpt run-multilingual-analysis --output=some/path/filename.yaml ...`
on an existing  `some/path/filename.yaml` overwrites the file. It would be nice if it could append results, especially for longer runs.
