### ISSUE TITLE
need spire logo

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/ontogpt#5]
(the Berkeley campanile, which is sort of a spire, could be an inspiration...)

**Comment by cmungall** [comment]
I think it would be appropriate to use an AI logo generator here

there was a vaguely Blakean theme going on with the naming (though HALO is now dead if openai killed code-davinci-002...)

**Comment by cmungall** [comment]
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/50745/228072004-1b250d4d-7719-4305-84d1-6bde02417fdd.png">

**Comment by nlharris** [comment]
very goth. i like the third of those the best.

**Comment by caufieldjh** [comment]
c/o the bing image creator: 
![image](https://github.com/monarch-initiative/ontogpt/assets/7987729/774b87e9-1438-4995-bc2f-539b8922e8ce)

**Comment by nlharris** [comment]
Not bad! What could the big bubbles at the foot of the spire represent?

**Comment by caufieldjh** [comment]
Clouds! For cloud compute, I suppose, since that's how most people will access LLMs.

**Comment by nlharris** [comment]
Ohh, clouds! Dark clouds. ⛈️

**Comment by nlharris** [comment]
what is the sort of white parallelogram cutting across the clouds?

**Comment by caufieldjh** [comment]
I think that's DALL-E getting creative. I vectorized it and cleaned it up a bit:
![spires1](https://github.com/monarch-initiative/ontogpt/assets/7987729/a95a3244-120e-46c1-8b83-7f24ccfd29f6)

**Comment by nlharris** [comment]
looks good!

**Comment by caufieldjh** [comment]
Going to consider this the SPIRES logo

**Comment by nlharris** [comment]
Did you commit this logo somewhere?

**Comment by caufieldjh** [comment]
Oops, no, I will. Reopening issue so I remember to do that.
