### ISSUE TITLE
Unexpected behavior with text argument

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/ontogpt#55]
[These lines](https://github.com/monarch-initiative/ontogpt/blob/df3c0d0e8040fd86283646ac106d5bc44773e961/src/ontogpt/cli.py#L186):

```
        if len(input) < 50 and Path(input).exists():
            text = open(input, "r").read()
        else:
            logging.info(f"Input {input} is not a file, assuming it is a string")
            text = input
```
seems useful for piping in text from another command on the command line, but seems likely to lead to unexpected behavior:

1) if a path to an input file is 50 or more characters long, it will silently be interpreted as input text, leading to unexpected output, example:

```
~/PythonProject/ontogpt $ extract -t disease_physiology.DiseasePhysiologyAnnotations really/long/path/name/for/some/reason/myInputFile.txt
ERROR:root:Line 'This text does not contain the necessary information to split into fields.' does not contain a colon; ignoring
```

2) if the user gives a path to an input file that does not exist, it will again be interpreted as input text, leading to confusing output

```
~/PythonProject/ontogpt $ extract -t disease_physiology.DiseasePhysiologyAnnotations oops/wrong/directory/myInputFile.txt
ERROR:root:Line 'This text does not contain the necessary information to split into fields.' does not contain a colon; ignoring
```

**Comment by cmungall** [comment]
Agreed. I think the most natural thing is to leave arguments for direct
text and make input path an option?
