### ISSUE TITLE
No ontogpt executable after make

### ISSUE THREAD

**Issue by MagdalenaZZ** [monarch-initiative/ontogpt#75]
Hi,

Thanks for a great initiative, can't wait to try it!

I set up a condaenv with py3.9

Added poetry and oaklib
conda install -c conda-forge poetry
pip install oaklib

Then followed readme steps from "Pre-requisites" onwards.

make worked fine

But the test case failed:
(py39) magz@Magdalenas-MacBook-Pro ontogpt % ontogpt extract -t mendelian_disease.MendelianDisease -i tests/input/cases/mendelian-disease-marfan.txt
zsh: command not found: ontogpt

So, I suppose there should be an executable called ontogpt, which I for some reason don't have?
Should I be in unix or bash for it to work? This is the make output (but it looks fine to me, no errors):

(py39) magz@Magdalenas-MacBook-Pro ontogpt % make
poetry run gen-project src/ontogpt/templates/core.yaml -d projects/core && cp -pr projects/core/docs docs/core
ALL_SCHEMAS = ['src/ontogpt/templates/core.yaml']
INFO:root:Generating: graphql
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/graphql
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
# metamodel_version: 1.7.0
INFO:root: graphql ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/core/graphql/core.graphql
INFO:root:Generating: jsonldcontext
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/jsonld
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: jsonldcontext ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/core/jsonld/core.context.jsonld
INFO:root:Generating: jsonld
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/jsonld
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: jsonld ARGS: {'mergeimports': True, 'context': 'projects/core/jsonld/core.context.jsonld'}
INFO:root:  WRITING TO: projects/core/jsonld/core.jsonld
INFO:root:Generating: jsonschema
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/jsonschema
INFO:root: jsonschema ARGS: {'mergeimports': True}
INFO:root:Importing linkml:types as /Users/magz/miniconda3/envs/py39/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types from source src/ontogpt/templates/core.yaml; base_dir=None
INFO:root:  WRITING TO: projects/core/jsonschema/core.schema.json
INFO:root:Generating: markdown
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/docs
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: markdown ARGS: {'mergeimports': True, 'directory': 'projects/core/docs', 'index_file': 'core.md'}
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
INFO:root:Generating: owl
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/owl
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: owl ARGS: {'mergeimports': True}
ERROR:root:Multiple slots with URI: http://w3id.org/ontogpt/core/id: ['namedEntity__id', 'publication__id']; consider giving each a unique slot_uri
ERROR:root:Multiple slots with URI: http://w3id.org/ontogpt/core/id: ['namedEntity__id', 'publication__id']; consider giving each a unique slot_uri
INFO:root:  WRITING TO: projects/core/owl/core.owl.ttl
INFO:root:Generating: prefixmap
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/prefixmap
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: prefixmap ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/core/prefixmap/core.yaml
INFO:root:Generating: proto
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/protobuf
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
 syntax="proto3";
 package
// metamodel_version: 1.7.0
INFO:root: proto ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/core/protobuf/core.proto
INFO:root:Generating: python
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: python ARGS: {'mergeimports': True}
INFO:root:CHECK: extractionResult__input_id => string
INFO:root:CHECK: extractionResult__input_title => string
INFO:root:CHECK: extractionResult__input_text => string
INFO:root:CHECK: extractionResult__raw_completion_output => string
INFO:root:CHECK: extractionResult__prompt => string
INFO:root:CHECK: extractionResult__extracted_object => Any
INFO:root:FALSE: OCCURS BEFORE: Any == Any owning: ExtractionResult
INFO:root:CHECK: extractionResult__named_entities => Any
INFO:root:FALSE: OCCURS BEFORE: Any == Any owning: ExtractionResult
INFO:root:CHECK: extractionResult__input_id => string
INFO:root:CHECK: extractionResult__input_title => string
INFO:root:CHECK: extractionResult__input_text => string
INFO:root:CHECK: extractionResult__raw_completion_output => string
INFO:root:CHECK: extractionResult__prompt => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__label => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__label => string
INFO:root:CHECK: triple__subject => NamedEntity
INFO:root:CHECK: triple__predicate => RelationshipType
INFO:root:CHECK: triple__object => NamedEntity
INFO:root:CHECK: triple__qualifier => string
INFO:root:CHECK: triple__subject_qualifier => NamedEntity
INFO:root:CHECK: triple__object_qualifier => NamedEntity
INFO:root:CHECK: triple__subject => NamedEntity
INFO:root:CHECK: triple__predicate => RelationshipType
INFO:root:CHECK: triple__object => NamedEntity
INFO:root:CHECK: triple__qualifier => string
INFO:root:CHECK: triple__subject_qualifier => NamedEntity
INFO:root:CHECK: triple__object_qualifier => NamedEntity
INFO:root:CHECK: textWithTriples__publication => Publication
INFO:root:TRUE: OCCURS SAME: TextWithTriples == Publication owning: TextWithTriples
INFO:root:CHECK: textWithTriples__triples => Triple
INFO:root:FALSE: OCCURS BEFORE: Triple == Triple owning: TextWithTriples
INFO:root:CHECK: textWithTriples__publication => Publication
INFO:root:TRUE: OCCURS SAME: TextWithTriples == Publication owning: TextWithTriples
INFO:root:CHECK: textWithTriples__triples => Triple
INFO:root:FALSE: OCCURS BEFORE: Triple == Triple owning: TextWithTriples
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: publication__id => string
INFO:root:CHECK: publication__title => string
INFO:root:CHECK: publication__abstract => string
INFO:root:CHECK: publication__combined_text => string
INFO:root:CHECK: publication__full_text => string
INFO:root:CHECK: publication__id => string
INFO:root:CHECK: publication__title => string
INFO:root:CHECK: publication__abstract => string
INFO:root:CHECK: publication__combined_text => string
INFO:root:CHECK: publication__full_text => string
INFO:root:CHECK: annotatorResult__subject_text => string
INFO:root:CHECK: annotatorResult__object_id => string
INFO:root:CHECK: annotatorResult__object_text => string
INFO:root:CHECK: annotatorResult__subject_text => string
INFO:root:CHECK: annotatorResult__object_id => string
INFO:root:CHECK: annotatorResult__object_text => string
INFO:root:CHECK: extractionResult__input_id => string
INFO:root:CHECK: extractionResult__input_title => string
INFO:root:CHECK: extractionResult__input_text => string
INFO:root:CHECK: extractionResult__raw_completion_output => string
INFO:root:CHECK: extractionResult__prompt => string
INFO:root:CHECK: extractionResult__extracted_object => Any
INFO:root:CHECK: extractionResult__named_entities => Any
INFO:root:CHECK: namedEntity__label => string
INFO:root:CHECK: triple__subject => NamedEntity
INFO:root:CHECK: triple__predicate => RelationshipType
INFO:root:CHECK: triple__object => NamedEntity
INFO:root:CHECK: triple__qualifier => string
INFO:root:CHECK: triple__subject_qualifier => NamedEntity
INFO:root:CHECK: triple__object_qualifier => NamedEntity
INFO:root:CHECK: textWithTriples__publication => Publication
INFO:root:CHECK: textWithTriples__triples => Triple
INFO:root:CHECK: publication__id => string
INFO:root:CHECK: publication__title => string
INFO:root:CHECK: publication__abstract => string
INFO:root:CHECK: publication__combined_text => string
INFO:root:CHECK: publication__full_text => string
INFO:root:CHECK: annotatorResult__subject_text => string
INFO:root:CHECK: annotatorResult__object_id => string
INFO:root:CHECK: annotatorResult__object_text => string
INFO:root:  WRITING TO: projects/core/core.py
INFO:root:Generating: shex
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/shex
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
# metamodel_version: 1.7.0
INFO:root: shex ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/core/shex/core.shex
INFO:root:Generating: shacl
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/shacl
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
# metamodel_version: 1.7.0
INFO:root: shacl ARGS: {'mergeimports': True}
INFO:root:Importing linkml:types as /Users/magz/miniconda3/envs/py39/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types from source src/ontogpt/templates/core.yaml; base_dir=None
INFO:root:  WRITING TO: projects/core/shacl/core.shacl.ttl
INFO:root:Generating: sqlddl
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/sqlschema
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
/* metamodel_version: 1.7.0 */
INFO:root: sqlddl ARGS: {'mergeimports': True}
INFO:root:No PK for Publication
INFO:root:  WRITING TO: projects/core/sqlschema/core.sql
INFO:root:Generating: excel
INFO:root: SCHEMA: src/ontogpt/templates/core.yaml
INFO:root: PARENT=projects/core/excel
INFO:root: excel ARGS: {'mergeimports': True, 'output': 'projects/core/excel/core.xlsx'}
INFO:root:Importing linkml:types as /Users/magz/miniconda3/envs/py39/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types from source src/ontogpt/templates/core.yaml; base_dir=None
poetry run gen-project src/ontogpt/templates/mendelian_disease.yaml -d projects/mendelian_disease && cp -pr projects/mendelian_disease/docs docs/mendelian_disease
ALL_SCHEMAS = ['src/ontogpt/templates/mendelian_disease.yaml']
INFO:root:Generating: graphql
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/graphql
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
# metamodel_version: 1.7.0
INFO:root: graphql ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/mendelian_disease/graphql/mendelian_disease.graphql
INFO:root:Generating: jsonldcontext
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/jsonld
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: jsonldcontext ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/mendelian_disease/jsonld/mendelian_disease.context.jsonld
INFO:root:Generating: jsonld
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/jsonld
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: jsonld ARGS: {'mergeimports': True, 'context': 'projects/mendelian_disease/jsonld/mendelian_disease.context.jsonld'}
INFO:root:  WRITING TO: projects/mendelian_disease/jsonld/mendelian_disease.jsonld
INFO:root:Generating: jsonschema
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/jsonschema
INFO:root: jsonschema ARGS: {'mergeimports': True}
INFO:root:Importing core as core from source src/ontogpt/templates/mendelian_disease.yaml; base_dir=src/ontogpt/templates
INFO:root:Importing linkml:types as /Users/magz/miniconda3/envs/py39/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types from source src/ontogpt/templates/mendelian_disease.yaml; base_dir=None
INFO:root:  WRITING TO: projects/mendelian_disease/jsonschema/mendelian_disease.schema.json
INFO:root:Generating: markdown
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/docs
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: markdown ARGS: {'mergeimports': True, 'directory': 'projects/mendelian_disease/docs', 'index_file': 'mendelian_disease.md'}
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
WARNING:root:Instantiating generator with another generator is deprecated
INFO:root:Generating: owl
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/owl
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: owl ARGS: {'mergeimports': True}
ERROR:root:Multiple slots with URI: http://w3id.org/ontogpt/core/id: ['namedEntity__id', 'publication__id']; consider giving each a unique slot_uri
ERROR:root:Multiple slots with URI: http://w3id.org/ontogpt/core/id: ['namedEntity__id', 'publication__id']; consider giving each a unique slot_uri
INFO:root:  WRITING TO: projects/mendelian_disease/owl/mendelian_disease.owl.ttl
INFO:root:Generating: prefixmap
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/prefixmap
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: prefixmap ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/mendelian_disease/prefixmap/mendelian_disease.yaml
INFO:root:Generating: proto
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/protobuf
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
 syntax="proto3";
 package
// metamodel_version: 1.7.0
INFO:root: proto ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/mendelian_disease/protobuf/mendelian_disease.proto
INFO:root:Generating: python
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
INFO:root: python ARGS: {'mergeimports': True}
INFO:root:CHECK: extractionResult__input_id => string
INFO:root:CHECK: extractionResult__input_title => string
INFO:root:CHECK: extractionResult__input_text => string
INFO:root:CHECK: extractionResult__raw_completion_output => string
INFO:root:CHECK: extractionResult__prompt => string
INFO:root:CHECK: extractionResult__extracted_object => Any
INFO:root:FALSE: OCCURS BEFORE: Any == Any owning: ExtractionResult
INFO:root:CHECK: extractionResult__named_entities => Any
INFO:root:FALSE: OCCURS BEFORE: Any == Any owning: ExtractionResult
INFO:root:CHECK: extractionResult__input_id => string
INFO:root:CHECK: extractionResult__input_title => string
INFO:root:CHECK: extractionResult__input_text => string
INFO:root:CHECK: extractionResult__raw_completion_output => string
INFO:root:CHECK: extractionResult__prompt => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__label => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__label => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: mendelianDisease__name => string
INFO:root:CHECK: mendelianDisease__description => string
INFO:root:CHECK: mendelianDisease__synonyms => string
INFO:root:CHECK: mendelianDisease__subclass_of => DiseaseCategory
INFO:root:CHECK: mendelianDisease__symptoms => Symptom
INFO:root:CHECK: mendelianDisease__inheritance => Inheritance
INFO:root:CHECK: mendelianDisease__genes => Gene
INFO:root:CHECK: mendelianDisease__disease_onsets => Onset
INFO:root:CHECK: mendelianDisease__publications => Publication
INFO:root:TRUE: OCCURS SAME: MendelianDisease == Publication owning: MendelianDisease
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: mendelianDisease__name => string
INFO:root:CHECK: mendelianDisease__description => string
INFO:root:CHECK: mendelianDisease__synonyms => string
INFO:root:CHECK: mendelianDisease__subclass_of => DiseaseCategory
INFO:root:CHECK: mendelianDisease__symptoms => Symptom
INFO:root:CHECK: mendelianDisease__inheritance => Inheritance
INFO:root:CHECK: mendelianDisease__genes => Gene
INFO:root:CHECK: mendelianDisease__disease_onsets => Onset
INFO:root:CHECK: mendelianDisease__publications => Publication
INFO:root:TRUE: OCCURS SAME: MendelianDisease == Publication owning: MendelianDisease
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: symptom__characteristic => string
INFO:root:CHECK: symptom__affects => string
INFO:root:CHECK: symptom__severity => string
INFO:root:CHECK: symptom__onset_of_symptom => Onset
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: symptom__characteristic => string
INFO:root:CHECK: symptom__affects => string
INFO:root:CHECK: symptom__severity => string
INFO:root:CHECK: symptom__onset_of_symptom => Onset
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: onset__years_old => string
INFO:root:CHECK: onset__decades => string
INFO:root:CHECK: onset__juvenile_or_adult => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: onset__years_old => string
INFO:root:CHECK: onset__decades => string
INFO:root:CHECK: onset__juvenile_or_adult => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: triple__subject => NamedEntity
INFO:root:CHECK: triple__predicate => RelationshipType
INFO:root:CHECK: triple__object => NamedEntity
INFO:root:CHECK: triple__qualifier => string
INFO:root:CHECK: triple__subject_qualifier => NamedEntity
INFO:root:CHECK: triple__object_qualifier => NamedEntity
INFO:root:CHECK: triple__subject => NamedEntity
INFO:root:CHECK: triple__predicate => RelationshipType
INFO:root:CHECK: triple__object => NamedEntity
INFO:root:CHECK: triple__qualifier => string
INFO:root:CHECK: triple__subject_qualifier => NamedEntity
INFO:root:CHECK: triple__object_qualifier => NamedEntity
INFO:root:CHECK: textWithTriples__publication => Publication
INFO:root:TRUE: OCCURS SAME: TextWithTriples == Publication owning: TextWithTriples
INFO:root:CHECK: textWithTriples__triples => Triple
INFO:root:FALSE: OCCURS BEFORE: Triple == Triple owning: TextWithTriples
INFO:root:CHECK: textWithTriples__publication => Publication
INFO:root:TRUE: OCCURS SAME: TextWithTriples == Publication owning: TextWithTriples
INFO:root:CHECK: textWithTriples__triples => Triple
INFO:root:FALSE: OCCURS BEFORE: Triple == Triple owning: TextWithTriples
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: namedEntity__id => string
INFO:root:CHECK: publication__id => string
INFO:root:CHECK: publication__title => string
INFO:root:CHECK: publication__abstract => string
INFO:root:CHECK: publication__combined_text => string
INFO:root:CHECK: publication__full_text => string
INFO:root:CHECK: publication__id => string
INFO:root:CHECK: publication__title => string
INFO:root:CHECK: publication__abstract => string
INFO:root:CHECK: publication__combined_text => string
INFO:root:CHECK: publication__full_text => string
INFO:root:CHECK: annotatorResult__subject_text => string
INFO:root:CHECK: annotatorResult__object_id => string
INFO:root:CHECK: annotatorResult__object_text => string
INFO:root:CHECK: annotatorResult__subject_text => string
INFO:root:CHECK: annotatorResult__object_id => string
INFO:root:CHECK: annotatorResult__object_text => string
INFO:root:CHECK: mendelianDisease__name => string
INFO:root:CHECK: mendelianDisease__description => string
INFO:root:CHECK: mendelianDisease__synonyms => string
INFO:root:CHECK: mendelianDisease__subclass_of => DiseaseCategory
INFO:root:CHECK: mendelianDisease__symptoms => Symptom
INFO:root:CHECK: mendelianDisease__inheritance => Inheritance
INFO:root:CHECK: mendelianDisease__genes => Gene
INFO:root:CHECK: mendelianDisease__disease_onsets => Onset
INFO:root:CHECK: mendelianDisease__publications => Publication
INFO:root:CHECK: symptom__characteristic => string
INFO:root:CHECK: symptom__affects => string
INFO:root:CHECK: symptom__severity => string
INFO:root:CHECK: symptom__onset_of_symptom => Onset
INFO:root:CHECK: onset__years_old => string
INFO:root:CHECK: onset__decades => string
INFO:root:CHECK: onset__juvenile_or_adult => string
INFO:root:CHECK: extractionResult__input_id => string
INFO:root:CHECK: extractionResult__input_title => string
INFO:root:CHECK: extractionResult__input_text => string
INFO:root:CHECK: extractionResult__raw_completion_output => string
INFO:root:CHECK: extractionResult__prompt => string
INFO:root:CHECK: extractionResult__extracted_object => Any
INFO:root:CHECK: extractionResult__named_entities => Any
INFO:root:CHECK: namedEntity__label => string
INFO:root:CHECK: triple__subject => NamedEntity
INFO:root:CHECK: triple__predicate => RelationshipType
INFO:root:CHECK: triple__object => NamedEntity
INFO:root:CHECK: triple__qualifier => string
INFO:root:CHECK: triple__subject_qualifier => NamedEntity
INFO:root:CHECK: triple__object_qualifier => NamedEntity
INFO:root:CHECK: textWithTriples__publication => Publication
INFO:root:CHECK: textWithTriples__triples => Triple
INFO:root:CHECK: publication__id => string
INFO:root:CHECK: publication__title => string
INFO:root:CHECK: publication__abstract => string
INFO:root:CHECK: publication__combined_text => string
INFO:root:CHECK: publication__full_text => string
INFO:root:CHECK: annotatorResult__subject_text => string
INFO:root:CHECK: annotatorResult__object_id => string
INFO:root:CHECK: annotatorResult__object_text => string
INFO:root:  WRITING TO: projects/mendelian_disease/mendelian_disease.py
INFO:root:Generating: shex
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/shex
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
# metamodel_version: 1.7.0
INFO:root: shex ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: projects/mendelian_disease/shex/mendelian_disease.shex
INFO:root:Generating: shacl
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/shacl
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
# metamodel_version: 1.7.0
INFO:root: shacl ARGS: {'mergeimports': True}
INFO:root:Importing core as core from source src/ontogpt/templates/mendelian_disease.yaml; base_dir=src/ontogpt/templates
INFO:root:Importing linkml:types as /Users/magz/miniconda3/envs/py39/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types from source src/ontogpt/templates/mendelian_disease.yaml; base_dir=None
INFO:root:  WRITING TO: projects/mendelian_disease/shacl/mendelian_disease.shacl.ttl
INFO:root:Generating: sqlddl
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/sqlschema
WARNING:root:File "core.yaml", line 59, col 19: Unrecognized prefix: rdfs
WARNING:root:Unrecognized prefix: MONDO
WARNING:root:Unrecognized prefix: HGNC
WARNING:root:Unrecognized prefix: HP
WARNING:root:Unrecognized prefix: RO
WARNING:root:Unrecognized prefix: biolink
/* metamodel_version: 1.7.0 */
INFO:root: sqlddl ARGS: {'mergeimports': True}
INFO:root:No PK for Publication
INFO:root:  WRITING TO: projects/mendelian_disease/sqlschema/mendelian_disease.sql
INFO:root:Generating: excel
INFO:root: SCHEMA: src/ontogpt/templates/mendelian_disease.yaml
INFO:root: PARENT=projects/mendelian_disease/excel
INFO:root: excel ARGS: {'mergeimports': True, 'output': 'projects/mendelian_disease/excel/mendelian_disease.xlsx'}
INFO:root:Importing core as core from source src/ontogpt/templates/mendelian_disease.yaml; base_dir=src/ontogpt/templates
INFO:root:Importing linkml:types as /Users/magz/miniconda3/envs/py39/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types from source src/ontogpt/templates/mendelian_disease.yaml; base_dir=None

**Comment by caufieldjh** [comment]
Hi @MagdalenaZZ,
Thanks for opening this issue. Does the command work if you precede it with `poetry run`, e.g.,
```
poetry run ontogpt extract -t mendelian_disease.MendelianDisease -i tests/input/cases/mendelian-disease-marfan.txt
```

**Comment by MagdalenaZZ** [comment]
conda install -c conda-forge poetry
pip install oaklib
poetry install
pip install html5lib

and a few makes got me there

Results looks really good, thank you guys!

**Comment by caufieldjh** [comment]
Great, glad it's working well now!
