### ISSUE TITLE
Add framework for interfacing with arbitrary LLM

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/ontogpt#93]
Current dependency on OpenAI API means OntoGPT is set up to assume that it will make API calls to a that resource, but to use other APIs and local resources we will need to generalize our API calls.
Perhaps a modular implementation system a la OAK is appropriate.

**Comment by cmungall** [comment]
or maybe just reuse an existing modular abstraction layer. Langchain?

**Comment by caufieldjh** [comment]
Oh neat. I'm going to try that first.

**Comment by caufieldjh** [comment]
Next steps:

- [ ] Retrieve remote models if necessary - use process like OAK
- [ ] Apply GPT4All models through Langchain
- [ ] Apply other local models through Langchain
- [ ] Tests for local models
- [ ] Support non-OpenAI APIs
- [ ] Tests for non-OpenAI APIs

**Comment by caufieldjh** [comment]
Extra bonus step:

- [ ] Add support for Huggingface Hub models through Langchain (note this needs to store another API key)

**Comment by caufieldjh** [comment]
Implemented in #373
